[package]
name = "wgx"
version = "0.14.0"
authors = ["Stefan Tammer <st.tammer@gmail.com>"]
edition = "2021"

[lib]
name = "wgx"
doctest = false

[workspace]
members = ["wgsl_modules", "wgsl_modules/loader", "wgsl_modules/macro"]

[features]
projection = ["dep:cgmath"]
wav_obj = ["projection"]
timer = ["dep:instant"]
glyph = ["dep:wgpu_glyph", "projection"]
iced = ["dep:iced_native", "dep:iced_winit", "dep:iced_wgpu"]
webgl = ["wgpu/webgl"]
wgsl_modules = ["dep:wgsl_modules"]
wgsl_modules_loader = ["wgsl_modules", "wgsl_modules/loader"]


[dependencies]
wgpu = "0.14"
raw-window-handle = "0.5"
arrayvec = "0.7"

# optional
cgmath = { version = "0", optional = true }
instant = { version = "0.1", features = ["now", "wasm-bindgen"], optional = true }
wgpu_glyph = { version = "0.18", optional = true }
iced_native = { version = "0.6", optional = true }
iced_winit = { version = "0.5", optional = true }
iced_wgpu = { version = "0.6", optional = true }
wgsl_modules = { path = "wgsl_modules", optional = true }


[dev-dependencies]
winit = "*"
futures = "*"
image = "*"
iced_graphics = { version = "*", features = ["canvas"] }
