[package]
name = "wgx"
version = "0.1.0"
authors = ["Stefan Tammer <st.tammer@gmail.com>"]
edition = "2021"

[lib]
name = "wgx"
doctest = false

[features]
# default = ["glyph", "iced"]
glyph = ["wgpu_glyph"]
iced = ["iced_winit", "iced_wgpu"]
spirv = ["glsl-to-spirv", "wgpu/spirv"]


[dependencies]
wgpu = { version = "0.12" }
futures = "0.3"
raw-window-handle = "0.4"
cgmath = "0.18"

# optional
glsl-to-spirv = { version = "0.1", optional = true }
wgpu_glyph = { version = "0.16", optional = true }
iced_winit = { git = "https://github.com/iced-rs/iced/", rev = "a53fa91", optional = true }
iced_wgpu = { git = "https://github.com/iced-rs/iced/", rev = "a53fa91", optional = true }


[dev-dependencies]
winit = "0.26"
image = "0.24"