[package]
name = "wgx"
version = "0.1.0"
authors = ["Stefan Tammer <st.tammer@gmail.com>"]
edition = "2018"

[lib]
name = "wgx"
doctest = false

[dependencies]
wgpu = "0.7"
raw-window-handle = "0.3"
glsl-to-spirv = "0.1"
cgmath = "0.18.0"
wgpu_glyph = "0.11.0"
winit = "0.24"
futures = "0.3"
image = "0.23"
