[package]
name = "wgx"
version = "0.1.0"
authors = ["Stefan Tammer <st.tammer@gmail.com>"]
edition = "2021"

[lib]
name = "wgx"
doctest = false

[features]
projection = ["cgmath"]
wav_obj = ["projection"]
frames = ["instant"]
glyph = ["wgpu_glyph", "projection"]
simple_text_input = ["glyph"]
iced = ["iced_winit", "iced_wgpu"]
webgl = ["wgpu/webgl"]


[dependencies]
wgpu = { version = "0.12" }
raw-window-handle = "0"

# optional
cgmath = { version = "0", optional = true }
instant = { version = "0.1", optional = true }
wgpu_glyph = { version = "0", optional = true }
iced_winit = { version = "0", optional = true }
iced_wgpu = { version = "0", optional = true }


[dev-dependencies]
winit = "*"
futures = "*"
image = "*"