[package]
name = "wgx"
version = "0.1.0"
authors = ["Stefan Tammer <st.tammer@gmail.com>"]
edition = "2021"

[lib]
name = "wgx"
doctest = false

[workspace]
members = ["wgsl_modules", "wgsl_modules/loader", "wgsl_modules/macro"]

[features]
projection = ["dep:cgmath"]
wav_obj = ["projection"]
ticks = ["dep:instant"]
glyph = ["dep:wgpu_glyph", "projection"]
iced = ["dep:iced_winit", "dep:iced_wgpu"]
webgl = ["wgpu/webgl"]
wgsl_modules = ["dep:wgsl_modules"]


[dependencies]
wgpu = { version = "0.13" }
raw-window-handle = "0.4"

# optional
cgmath = { version = "0", optional = true }
instant = { version = "0.1", features = ["now", "wasm-bindgen"], optional = true }
wgpu_glyph = { version = "0", optional = true }
iced_winit = { git = "https://github.com/iced-rs/iced/", rev = "8b250d1", optional = true }
iced_wgpu = { git = "https://github.com/iced-rs/iced/", rev = "8b250d1", optional = true }
wgsl_modules = { path = "wgsl_modules", optional = true }


[dev-dependencies]
winit = "0.26"
futures = "*"
image = "*"