[package]
name = "wgx"
version = "0.22.0"
authors = ["Stefan Tammer <st.tammer@gmail.com>"]
edition = "2021"
license = "MIT"

[lib]
name = "wgx"


# wgsl modules
[workspace]
members = ["wgsl_modules", "wgsl_modules/loader", "wgsl_modules/macro"]

[workspace.package]
version = "0.22.0"
authors = ["Stefan Tammer <st.tammer@gmail.com>"]
edition = "2021"
license = "MIT"

[workspace.dependencies]
wgsl_modules = { version = "~0.22.0", path = "wgsl_modules" }
wgsl_modules_macro = { version = "~0.22.0", path = "wgsl_modules/macro" }
wgsl_modules_loader = { version = "~0.22.0", path = "wgsl_modules/loader" }
naga = { version = "22", features = ["wgsl-in"] }


[features]
default = ["math", "wgsl_modules"]
math = ["dep:glam"]
wgsl_modules = ["dep:wgsl_modules"]
wgsl_modules_loader = ["wgsl_modules", "wgsl_modules/loader"]


[dependencies]
wgpu = { version = "22", default-features = false, features = ["wgsl"] }
wgpu-types = "22"
arrayvec = "0.7"

# optional
glam = { version = "0", optional = true }
wgsl_modules = { workspace = true, optional = true }


# [patch."https://github.com/StT191/wgx-platform"]
# platform = { path = "../platform" }

[dev-dependencies]
platform = { version = "0.4.7", tag = "v0.4.7", git = "https://github.com/StT191/wgx-platform", features = ["frame_timer"] }
image = { version = "0.25", default-features = false, features = ["png"] }
wgpu = { version = "22", default-features = false, features = ["webgpu", "webgl"] }