[package]
name = "wgx"
version = "0.15.1"
authors = ["Stefan Tammer <st.tammer@gmail.com>"]
edition = "2021"
license = "MIT"

[lib]
name = "wgx"
doctest = false


# wgsl modules
[workspace]
members = ["wgsl_modules", "wgsl_modules/loader", "wgsl_modules/macro"]

[workspace.package]
version = "0.15.1"
authors = ["Stefan Tammer <st.tammer@gmail.com>"]
edition = "2021"
license = "MIT"

[workspace.dependencies]
wgsl_modules_macro = { version = "0.15.1", path = "wgsl_modules/macro" }
wgsl_modules_loader = { version = "0.15.1", path = "wgsl_modules/loader" }


[features]
projection = ["dep:cgmath"]
wav_obj = ["projection"]
timer = ["dep:instant"]
glyph = ["dep:wgpu_glyph", "projection"]
webgl = ["wgpu/webgl"]
wgsl_modules = ["dep:wgsl_modules"]
wgsl_modules_loader = ["wgsl_modules", "wgsl_modules/loader"]


[dependencies]
wgpu = "0.15"
wgpu-types = "0.15"
raw-window-handle = "0.5"
arrayvec = "0.7"

# optional
cgmath = { version = "0", optional = true }
instant = { version = "0.1", features = ["wasm-bindgen"], optional = true }
wgpu_glyph = { version = "0.19", optional = true }
wgsl_modules = { version = "0.15.0", path = "wgsl_modules", optional = true }


[dev-dependencies]
winit = "0.28"
pollster = "0.2"
png = "0.17"