[package]
name = "wgfx"
version = "0.1.0"
authors = ["Stefan Tammer <st.tammer@gmail.com>"]
edition = "2018"

[lib]
name = "wgfx"
doctest = false

[dependencies]
wgpu = "0.4"
winit = "0.20"
glsl-to-spirv = "0.1"