[package]
name = "wgfx"
version = "0.1.0"
authors = ["Stefan Tammer <st.tammer@gmail.com>"]
edition = "2018"

[lib]
name = "wgfx"
doctest = false

[dependencies]
wgpu = "0.5"
winit = "0.22"
futures = "0.3"
glsl-to-spirv = "0.1"
zerocopy = "0.2"