[package]
name = "wgx"
version = "0.1.0"
authors = ["Stefan Tammer <st.tammer@gmail.com>"]
edition = "2018"
resolver = "2"

[lib]
name = "wgx"
doctest = false

[features]
default = ["glyph", "spirv"]
glyph = ["wgpu_glyph"]
spirv = ["glsl-to-spirv", "wgpu/spirv"]

[dependencies]
wgpu = { version = "0.10" }
futures = "0.3"
raw-window-handle = "0.3"
cgmath = "0.18"
glsl-to-spirv = { version = "0.1", optional = true }
wgpu_glyph = { version = "0.14", optional = true }

[dev-dependencies]
winit = "0.25"
image = "0.23"