[package]
name = "wgsl_modules_macro"
version = "0.1.0"
authors = ["Stefan Tammer <st.tammer@gmail.com>"]
edition = "2021"

[lib]
name = "wgsl_modules_macro"
proc-macro = true

[dependencies]
proc-macro2 = "1"
syn = "1"
quote = "1"
wgsl_modules_loader = { path = "../loader" }
