[package]
name = "wgsl_modules_loader"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "wgsl_modules_loader"

[dependencies]
tree-sitter = "0"
tree-sitter-wgsl = "0"
lazy_static = "1"
regex = { version = "1", features = ["unicode-perl"] }